name: Generate site

on:
  repository_dispatch:
    types: [contentful.deploy]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: USER
          server-password: TOKEN

      - name: Restore jar cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: generator.jar
          key: ${{ github.sha }}

      - name: Install
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: mvn dependency:get -DremoteRepositories=github::::https://maven.pkg.github.com/Cartman-Digital/www.cartman.fi -Ddest=. -DgroupId=com.github.Cartman-Digital -DartifactId=generator -Dversion=1.0.0-${SHORT_SHA} -Dtransitive=false && mv generator-1.0.0-${SHORT_SHA}.jar generator.jar
        env:
          TOKEN: "${{ secrets.MVN_PAT }}"
          USER: paveq

      - name: Save jar cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        id: cache-jar
        uses: actions/cache/save@v3
        with:
          path: generator.jar
          key: ${{ github.sha }}

      - name: Generate
        run: java -jar generator.jar -generate
        env:
          CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
          CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
          CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
          BASE_URL: "${{ vars.BASE_URL }}"

      - name: Move static assets
        run: mv repo/resources/public/* build/

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'
          skip_install: true

      - name: Upload
        run: gsutil -m rsync -d -r build gs://www-cartman-fi-prod
