name: Generate site

on:
  repository_dispatch:
    types: [publish-event]
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cartman-digital/www.cartman.fi:main
      options: --cpus 1
      env:
        CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
        CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
        CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
    steps:
      - name: Generate
        run: java -jar /app/generator-standalone.jar -generate

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'

      - name: Upload
        run: gsutil -m rsync -d -r /__w/www.cartman.fi/www.cartman.fi/build gs://www-cartman-fi-prod


# name: Generate site

# on:
#   repository_dispatch:
#     types: [publish-event]
#   workflow_dispatch:

# jobs:
#   generate:
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#       packages: 'read'
#     runs-on: ubuntu-latest
#     container:
#       image: ghcr.io/cartman-digital/www.cartman.fi:main
#       options: --cpus 1
#       env:
#         CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
#         CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
#         CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
#     steps:
#       - name: Generate
#         run: java -jar /app/generator-standalone.jar -generate

#       - id: 'auth'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
#           service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'

#       - id: 'upload-files'
#         uses: 'google-github-actions/upload-cloud-storage@v1'
#         with:
#           path: '/__w/www.cartman.fi/www.cartman.fi/build'
#           destination: 'www-cartman-fi-prod'
#           parent: false