name: Generate site

on:
  repository_dispatch:
    types: [publish-event]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cartman-digital/www.cartman.fi:main
      volumes:
        - output:/app/build
      options: --cpus 1
      env:
        CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
        CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
        CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
    steps:
      - name: Generate
        run: env && java -jar /app/generator-standalone.jar -generate

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'

      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'output'
          destination: 'www-cartman-fi-prod'
          parent: false




# name: Generate site

# on:
#   repository_dispatch:
#     types: [publish-event]
#   workflow_dispatch:

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     container:
#       image: ghcr.io/cartman-digital/www.cartman.fi:main
#       volumes:
#         - output:/app/build
#       options: --cpus 1
#       env:
#         CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
#         CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
#         CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
#     steps:
#       - name: Generate
#         run: env && java -jar /app/generator-standalone.jar -generate

#       - uses: actions/upload-artifact@v3
#         with:
#           name: site
#           path: output/

#   upload:
#     runs-on: ubuntu-latest
#     needs: generate
#     permissions:
#       contents: read
#       packages: write

#     steps:
#     - uses: actions/checkout@v3

#     - uses: actions/download-artifact@v3
#       with:
#         name: site

#     - id: 'auth'
#       uses: 'google-github-actions/auth@v1'
#       with:
#         workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
#         service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'