name: Generate site

on:
  repository_dispatch:
    types: [publish-event]
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/cartman-digital/www.cartman.fi:main
    #   options: --cpus 1
    #   env:
    #     CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
    #     CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
    #     CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
    #     BASE_URL: "${{ vars.BASE_URL }}"
    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: paveq
          server-password: "${{ secrets.MVN_PAT }}"

      - name: testing
        run: cat ~/.m2/settings.xml


      - name: Install
        run: mvn dependency:get -DremoteRepositories=github::::https://maven.pkg.github.com/Cartman-Digital/www.cartman.fi -Ddest=. -DgroupId=com.github.Cartman-Digital -DartifactId=generator -Dversion=1.0.0 -Dtransitive=false

      - name: Generate
        run: java -jar /app/generator.jar -generate
        env:
          CONTENTFUL_ENVIRONMENT: "${{ vars.CONTENTFUL_ENVIRONMENT }}"
          CONTENTFUL_SPACE: "${{ vars.CONTENTFUL_SPACE }}"
          CONTENTFUL_TOKEN: "${{ secrets.CONTENTFUL_TOKEN }}"
          BASE_URL: "${{ vars.BASE_URL }}"

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/43005639550/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-uploader@www-cartman-fi.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'

      - name: Upload
        run: gsutil -m rsync -d -r build gs://www-cartman-fi-prod
